### PR TITLE
Updated the NGINX entry to write logs for data files accessed

### PR DESCRIPTION
**Pull request by Johanndutoit**
Trigger happy devops days for me made me disable the access log for the data domain.

This will write the logs to the folder that is later picked up and parsed by log checker later

### CODE REVIEW

**Comment by Johanndutoit** [comment]
@jonathanendersby @bruskiza ^

**Comment by bruskiza** [comment]
potentially :-1: because:

```

goddard@00003:/var/log/nginx$ curl http://data.mamawifi.com/floobar
goddard@00003:/var/log/nginx$ grep floobar access.log
192.168.88.50 - - [18/Feb/2016:11:03:43 +0000] "GET /floobar HTTP/1.1" 404 162 "-" "curl/7.35.0"
goddard@00003:/var/log/nginx$ 

```

Am I correct in the logic here?

It defaults to access.log if not explicitly specified?
Testing says: yes.

Thoughts?

**Comment by Johanndutoit** [comment]
@bruskiza interesting.

So my assumption was that as long as we have a access log that can be parsed the video's can be tracked for download count.

And this is picked up on your side with a script that loads that into piwik ?

**Comment by bruskiza** [comment]
Yep. Can you do some further testing on your node to see if the access log does in fact have video downloads?

I will in the meantime, check to see what piwik is doing with the access.logs

**Comment by Johanndutoit** [comment]
@bruskiza roger will check this side real quick to double check.

**Comment by Johanndutoit** [comment]
Hi

Ok so double checked the videos are begin tracked and all is good, they are listed:

```
172.17.0.3 - - [17/Feb/2016:11:32:02 +0000] "HEAD /media/gem/medical_procedures/Manual_Removal_of_the_Placenta.mp4.3gp HTTP/1.1" 200 0 "-" "-"
172.17.0.3 - - [17/Feb/2016:11:32:02 +0000] "HEAD /media/gem/medical_procedures/Newborn_Care_Series_-_Newborn_Physical_Exam-8foaEYKfDRo.f136.mp4.3gp HTTP/1.1" 200 0 "-" "-"
172.17.0.3 - - [17/Feb/2016:11:32:02 +0000] "HEAD /media/gem/medical_procedures/Newborn_Care_Series_-_Setting_Up_an_IV_Line-rb5pz-0Q5II.mp4.3gp HTTP/1.1" 200 0 "-" "-"
172.17.0.3 - - [17/Feb/2016:11:32:02 +0000] "HEAD /media/gem/medical_procedures/Newborn_Care_Series_-_Taking_a_Heel_Blood_Sample-MieKJa5YJd4.mp4.3gp HTTP/1.1" 200 0 "-" "-"
172.17.0.3 - - [17/Feb/2016:11:32:02 +0000] "HEAD /media/gem/medical_procedures/Newborn_Care_-_Taking_a_Venous_Blood_Sample-5FfVjiou_YE.mp4.3gp HTTP/1.1" 200 0 "-" "-"
192.168.88.50 - - [17/Feb/2016:11:44:57 +0000] "HEAD /media/gem/medical_procedures/Newborn_Care_Series_-_Taking_a_Heel_Blood_Sample-MieKJa5YJd4.mp4.3gp HTTP/1.1" 200 0 "-" "curl/7.35.0"
```

Let me know if ^ is what you'd need to count the downloads

**Comment by Johanndutoit** [comment]
Actually checking something else, just noticed "CURL" on that. BRB

**Comment by bruskiza** [comment]
head is not download.
I want to see a get.

**Comment by Johanndutoit** [comment]
Yeah my bad on that, was a older log.

Checked it from browser and got:

```
192.168.88.248 - - [18/Feb/2016:11:20:37 +0000] "GET /media/gem/family_health/How%20to%20Plan%20Pregnancy.mp4.3gp HTTP/1.1" 206 304 "http://mamawifi.com/family-health/video/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"

192.168.88.248 - - [18/Feb/2016:11:22:05 +0000] "GET /media/gem/newborn_health/How_to_care_for_a_newborn_-_The_first_hours_after_delivery.mp4.3gp HTTP/1.1" 206 273298 "http://mamawifi.com/newborn-health/video/3" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
```

When watching the video.

So seems good, does a GET for the .3gp. And it does this as soon as I hit play on a video, which is what we want if I understand correctly.

**Comment by bruskiza** [comment]
Manythanks @Johanndutoit

**Pull request merged**
