### PR TITLE
Feature/logs

### PR DESCRIPTION
**Pull request by Johanndutoit**
Updated to push logs to server in a slug form of the current date and time. Using the layout:

``` bash
/var/log/node/5/2015/04/20150401133400.tar.gz
```

### CODE REVIEW

**Comment by Johanndutoit** [comment]
And syncs are deleted afterwards so these uploads can be treated as "snapshots"

**Comment by Johanndutoit** [comment]
@skibz @jonathanendersby @BarryBotha thoughts ?

**Comment by jonathanendersby** [comment]
Yeah I like it. Clean! +1

**Comment by skibz** [comment]
:+1:

**Pull request merged**
