### PR TITLE
Updated the settings to allow for new website settings to take affect

### PR DESCRIPTION
**Pull request by Johanndutoit**
Updated according to email from @jonathanendersby to allow new SSID and websites through walled garden

### CODE REVIEW

**Comment by Johanndutoit** [comment]
@skibz @BarryBotha thoughts ?

**Comment by skibz** [comment]
looks good, man. :+1:

**Comment by smn** [comment]
Is this PR still relevant?

**Comment by Johanndutoit** [comment]
@smn was added just to keep the big overall config up to date with what is being applied from the CaptivePortal right now

**Pull request merged**
